//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Characteristic_type.
    /// </summary>
    //  *** Start programmer edit section *** (characteristicType CustomAttributes)

    //  *** End programmer edit section *** (characteristicType CustomAttributes)
    [AutoAltered()]
    [Caption("characteristic_type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("characteristic_typeE", new string[] {
            "regex as \'Regex\'",
            "description as \'Description\'"})]
    [View("characteristic_typeL", new string[] {
            "regex as \'Regex\'",
            "description as \'Description\'"})]
    public class characteristicType : ICSSoft.STORMNET.DataObject
    {
        
        private string fregex;
        
        private string fdescription;
        
        //  *** Start programmer edit section *** (characteristicType CustomMembers)

        //  *** End programmer edit section *** (characteristicType CustomMembers)

        
        /// <summary>
        /// regex.
        /// </summary>
        //  *** Start programmer edit section *** (characteristicType.regex CustomAttributes)

        //  *** End programmer edit section *** (characteristicType.regex CustomAttributes)
        [StrLen(255)]
        public virtual string regex
        {
            get
            {
                //  *** Start programmer edit section *** (characteristicType.regex Get start)

                //  *** End programmer edit section *** (characteristicType.regex Get start)
                string result = this.fregex;
                //  *** Start programmer edit section *** (characteristicType.regex Get end)

                //  *** End programmer edit section *** (characteristicType.regex Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (characteristicType.regex Set start)

                //  *** End programmer edit section *** (characteristicType.regex Set start)
                this.fregex = value;
                //  *** Start programmer edit section *** (characteristicType.regex Set end)

                //  *** End programmer edit section *** (characteristicType.regex Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (characteristicType.description CustomAttributes)

        //  *** End programmer edit section *** (characteristicType.description CustomAttributes)
        [StrLen(255)]
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (characteristicType.description Get start)

                //  *** End programmer edit section *** (characteristicType.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (characteristicType.description Get end)

                //  *** End programmer edit section *** (characteristicType.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (characteristicType.description Set start)

                //  *** End programmer edit section *** (characteristicType.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (characteristicType.description Set end)

                //  *** End programmer edit section *** (characteristicType.description Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "characteristic_typeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View characteristic_typeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("characteristic_typeE", typeof(DataLine.xgvlk98.characteristicType));
                }
            }
            
            /// <summary>
            /// "characteristic_typeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View characteristic_typeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("characteristic_typeL", typeof(DataLine.xgvlk98.characteristicType));
                }
            }
        }
    }
}
