//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Resource_spec.
    /// </summary>
    //  *** Start programmer edit section *** (resourceSpec CustomAttributes)

    //  *** End programmer edit section *** (resourceSpec CustomAttributes)
    [AutoAltered()]
    [Caption("resource_spec")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("resource_specE", new string[] {
            "enum as \'Enum\'",
            "type as \'Type\'",
            "existent as \'Existent\'",
            "shared as \'Shared\'",
            "version as \'Version\'",
            "name as \'Name\'",
            "description as \'Description\'",
            "category as \'Category\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "parent_id as \'Parent_id\'",
            "parent_id.enum as \'Enum\'",
            "parent_service_spec_id as \'Parent_service_spec_id\'",
            "parent_service_spec_id.enum as \'Enum\'",
            "cardinality as \'Cardinality\'",
            "cardinality.description as \'Description\'",
            "resource_common_id as \'Resource_common_id\'",
            "resource_common_id.external_id as \'External_id\'"})]
    [View("resource_specL", new string[] {
            "enum as \'Enum\'",
            "type as \'Type\'",
            "existent as \'Existent\'",
            "shared as \'Shared\'",
            "version as \'Version\'",
            "name as \'Name\'",
            "description as \'Description\'",
            "category as \'Category\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "parent_id as \'Enum\'",
            "parent_service_spec_id as \'Enum\'",
            "cardinality as \'Description\'",
            "cardinality as \'Description\'",
            "resource_common_id as \'External_id\'",
            "parent_service_spec_id as \'Enum\'",
            "resource_common_id as \'External_id\'"}, Hidden=new string[] {
            "parent_id",
            "parent_service_spec_id",
            "cardinality",
            "cardinality",
            "resource_common_id",
            "parent_service_spec_id",
            "resource_common_id"})]
    public class resourceSpec : ICSSoft.STORMNET.DataObject
    {
        
        private string fenum;
        
        private string ftype;
        
        private bool fexistent;
        
        private bool fshared;
        
        private int fversion;
        
        private string fname;
        
        private string fdescription;
        
        private string fcategory;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private DataLine.xgvlk98.cardinalityType fcardinality;
        
        private DataLine.xgvlk98.resourceSpec fparent_id;
        
        private DataLine.xgvlk98.serviceSpec fparent_service_spec_id;
        
        private DataLine.xgvlk98.resourceCommon fresource_common_id;
        
        //  *** Start programmer edit section *** (resourceSpec CustomMembers)

        //  *** End programmer edit section *** (resourceSpec CustomMembers)

        
        /// <summary>
        /// enum.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.enum CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.enum CustomAttributes)
        [StrLen(32)]
        [NotNull()]
        public virtual string @enum
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.enum Get start)

                //  *** End programmer edit section *** (resourceSpec.enum Get start)
                string result = this.fenum;
                //  *** Start programmer edit section *** (resourceSpec.enum Get end)

                //  *** End programmer edit section *** (resourceSpec.enum Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.enum Set start)

                //  *** End programmer edit section *** (resourceSpec.enum Set start)
                this.fenum = value;
                //  *** Start programmer edit section *** (resourceSpec.enum Set end)

                //  *** End programmer edit section *** (resourceSpec.enum Set end)
            }
        }
        
        /// <summary>
        /// type.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.type CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.type CustomAttributes)
        [StrLen(32)]
        [NotNull()]
        public virtual string type
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.type Get start)

                //  *** End programmer edit section *** (resourceSpec.type Get start)
                string result = this.ftype;
                //  *** Start programmer edit section *** (resourceSpec.type Get end)

                //  *** End programmer edit section *** (resourceSpec.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.type Set start)

                //  *** End programmer edit section *** (resourceSpec.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (resourceSpec.type Set end)

                //  *** End programmer edit section *** (resourceSpec.type Set end)
            }
        }
        
        /// <summary>
        /// existent.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.existent CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.existent CustomAttributes)
        [NotNull()]
        public virtual bool existent
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.existent Get start)

                //  *** End programmer edit section *** (resourceSpec.existent Get start)
                bool result = this.fexistent;
                //  *** Start programmer edit section *** (resourceSpec.existent Get end)

                //  *** End programmer edit section *** (resourceSpec.existent Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.existent Set start)

                //  *** End programmer edit section *** (resourceSpec.existent Set start)
                this.fexistent = value;
                //  *** Start programmer edit section *** (resourceSpec.existent Set end)

                //  *** End programmer edit section *** (resourceSpec.existent Set end)
            }
        }
        
        /// <summary>
        /// shared.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.shared CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.shared CustomAttributes)
        [NotNull()]
        public virtual bool shared
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.shared Get start)

                //  *** End programmer edit section *** (resourceSpec.shared Get start)
                bool result = this.fshared;
                //  *** Start programmer edit section *** (resourceSpec.shared Get end)

                //  *** End programmer edit section *** (resourceSpec.shared Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.shared Set start)

                //  *** End programmer edit section *** (resourceSpec.shared Set start)
                this.fshared = value;
                //  *** Start programmer edit section *** (resourceSpec.shared Set end)

                //  *** End programmer edit section *** (resourceSpec.shared Set end)
            }
        }
        
        /// <summary>
        /// version.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.version CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.version CustomAttributes)
        [NotNull()]
        public virtual int version
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.version Get start)

                //  *** End programmer edit section *** (resourceSpec.version Get start)
                int result = this.fversion;
                //  *** Start programmer edit section *** (resourceSpec.version Get end)

                //  *** End programmer edit section *** (resourceSpec.version Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.version Set start)

                //  *** End programmer edit section *** (resourceSpec.version Set start)
                this.fversion = value;
                //  *** Start programmer edit section *** (resourceSpec.version Set end)

                //  *** End programmer edit section *** (resourceSpec.version Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.name CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.name Get start)

                //  *** End programmer edit section *** (resourceSpec.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (resourceSpec.name Get end)

                //  *** End programmer edit section *** (resourceSpec.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.name Set start)

                //  *** End programmer edit section *** (resourceSpec.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (resourceSpec.name Set end)

                //  *** End programmer edit section *** (resourceSpec.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.description CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.description CustomAttributes)
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.description Get start)

                //  *** End programmer edit section *** (resourceSpec.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (resourceSpec.description Get end)

                //  *** End programmer edit section *** (resourceSpec.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.description Set start)

                //  *** End programmer edit section *** (resourceSpec.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (resourceSpec.description Set end)

                //  *** End programmer edit section *** (resourceSpec.description Set end)
            }
        }
        
        /// <summary>
        /// category.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.category CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.category CustomAttributes)
        [StrLen(32)]
        [NotNull()]
        public virtual string category
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.category Get start)

                //  *** End programmer edit section *** (resourceSpec.category Get start)
                string result = this.fcategory;
                //  *** Start programmer edit section *** (resourceSpec.category Get end)

                //  *** End programmer edit section *** (resourceSpec.category Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.category Set start)

                //  *** End programmer edit section *** (resourceSpec.category Set start)
                this.fcategory = value;
                //  *** Start programmer edit section *** (resourceSpec.category Set end)

                //  *** End programmer edit section *** (resourceSpec.category Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.dt_created CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.dt_created CustomAttributes)
        [NotNull()]
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.dt_created Get start)

                //  *** End programmer edit section *** (resourceSpec.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (resourceSpec.dt_created Get end)

                //  *** End programmer edit section *** (resourceSpec.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.dt_created Set start)

                //  *** End programmer edit section *** (resourceSpec.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (resourceSpec.dt_created Set end)

                //  *** End programmer edit section *** (resourceSpec.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.dt_modified CustomAttributes)
        [NotNull()]
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.dt_modified Get start)

                //  *** End programmer edit section *** (resourceSpec.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (resourceSpec.dt_modified Get end)

                //  *** End programmer edit section *** (resourceSpec.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.dt_modified Set start)

                //  *** End programmer edit section *** (resourceSpec.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (resourceSpec.dt_modified Set end)

                //  *** End programmer edit section *** (resourceSpec.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.cardinality CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.cardinality CustomAttributes)
        [PropertyStorage(new string[] {
                "cardinality"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.cardinalityType cardinality
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.cardinality Get start)

                //  *** End programmer edit section *** (resourceSpec.cardinality Get start)
                DataLine.xgvlk98.cardinalityType result = this.fcardinality;
                //  *** Start programmer edit section *** (resourceSpec.cardinality Get end)

                //  *** End programmer edit section *** (resourceSpec.cardinality Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.cardinality Set start)

                //  *** End programmer edit section *** (resourceSpec.cardinality Set start)
                this.fcardinality = value;
                //  *** Start programmer edit section *** (resourceSpec.cardinality Set end)

                //  *** End programmer edit section *** (resourceSpec.cardinality Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.parent_id CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.parent_id CustomAttributes)
        [PropertyStorage(new string[] {
                "parent_id"})]
        public virtual DataLine.xgvlk98.resourceSpec parent_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.parent_id Get start)

                //  *** End programmer edit section *** (resourceSpec.parent_id Get start)
                DataLine.xgvlk98.resourceSpec result = this.fparent_id;
                //  *** Start programmer edit section *** (resourceSpec.parent_id Get end)

                //  *** End programmer edit section *** (resourceSpec.parent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.parent_id Set start)

                //  *** End programmer edit section *** (resourceSpec.parent_id Set start)
                this.fparent_id = value;
                //  *** Start programmer edit section *** (resourceSpec.parent_id Set end)

                //  *** End programmer edit section *** (resourceSpec.parent_id Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.parent_service_spec_id CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.parent_service_spec_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.xgvlk98.serviceSpec parent_service_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.parent_service_spec_id Get start)

                //  *** End programmer edit section *** (resourceSpec.parent_service_spec_id Get start)
                DataLine.xgvlk98.serviceSpec result = this.fparent_service_spec_id;
                //  *** Start programmer edit section *** (resourceSpec.parent_service_spec_id Get end)

                //  *** End programmer edit section *** (resourceSpec.parent_service_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.parent_service_spec_id Set start)

                //  *** End programmer edit section *** (resourceSpec.parent_service_spec_id Set start)
                this.fparent_service_spec_id = value;
                //  *** Start programmer edit section *** (resourceSpec.parent_service_spec_id Set end)

                //  *** End programmer edit section *** (resourceSpec.parent_service_spec_id Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpec.resource_common_id CustomAttributes)

        //  *** End programmer edit section *** (resourceSpec.resource_common_id CustomAttributes)
        [PropertyStorage(new string[] {
                "resource_common_id"})]
        public virtual DataLine.xgvlk98.resourceCommon resource_common_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpec.resource_common_id Get start)

                //  *** End programmer edit section *** (resourceSpec.resource_common_id Get start)
                DataLine.xgvlk98.resourceCommon result = this.fresource_common_id;
                //  *** Start programmer edit section *** (resourceSpec.resource_common_id Get end)

                //  *** End programmer edit section *** (resourceSpec.resource_common_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpec.resource_common_id Set start)

                //  *** End programmer edit section *** (resourceSpec.resource_common_id Set start)
                this.fresource_common_id = value;
                //  *** Start programmer edit section *** (resourceSpec.resource_common_id Set end)

                //  *** End programmer edit section *** (resourceSpec.resource_common_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "resource_specE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_specE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_specE", typeof(DataLine.xgvlk98.resourceSpec));
                }
            }
            
            /// <summary>
            /// "resource_specL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_specL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_specL", typeof(DataLine.xgvlk98.resourceSpec));
                }
            }
        }
    }
}
