//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Resource_spec_characteristic.
    /// </summary>
    //  *** Start programmer edit section *** (resourceSpecCharacteristic CustomAttributes)

    //  *** End programmer edit section *** (resourceSpecCharacteristic CustomAttributes)
    [AutoAltered()]
    [Caption("resource_spec_characteristic")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("resource_spec_characteristicE", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "can_be_overridden as \'Can_be_overridden\'",
            "label as \'Label\'",
            "list as \'List\'",
            "type as \'Type\'",
            "type.regex as \'Regex\'",
            "resource_spec_id as \'Resource_spec_id\'",
            "resource_spec_id.enum as \'Enum\'",
            "dictionary_id as \'Dictionary_id\'",
            "dictionary_id.name as \'Name\'"})]
    [View("resource_spec_characteristicL", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "can_be_overridden as \'Can_be_overridden\'",
            "label as \'Label\'",
            "list as \'List\'",
            "type.regex as \'Regex\'",
            "resource_spec_id.enum as \'Enum\'",
            "dictionary_id.name as \'Name\'"})]
    public class resourceSpecCharacteristic : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fvalue;
        
        private bool fcan_be_overridden;
        
        private string flabel;
        
        private int flist;
        
        private DataLine.xgvlk98.resourceSpec fresource_spec_id;
        
        private DataLine.xgvlk98.characteristicType ftype;
        
        private DataLine.xgvlk98.dictionary fdictionary_id;
        
        //  *** Start programmer edit section *** (resourceSpecCharacteristic CustomMembers)

        //  *** End programmer edit section *** (resourceSpecCharacteristic CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.name CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.name Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.name Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.name Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.name Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.name Set end)
            }
        }
        
        /// <summary>
        /// value.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.value CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.value CustomAttributes)
        [StrLen(255)]
        public virtual string value
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.value Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.value Get start)
                string result = this.fvalue;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.value Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.value Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.value Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.value Set start)
                this.fvalue = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.value Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.value Set end)
            }
        }
        
        /// <summary>
        /// can_be_overridden.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.can_be_overridden CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.can_be_overridden CustomAttributes)
        [NotNull()]
        public virtual bool can_be_overridden
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Get start)
                bool result = this.fcan_be_overridden;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Set start)
                this.fcan_be_overridden = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.can_be_overridden Set end)
            }
        }
        
        /// <summary>
        /// label.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.label CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.label CustomAttributes)
        [StrLen(255)]
        public virtual string label
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.label Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.label Get start)
                string result = this.flabel;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.label Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.label Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.label Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.label Set start)
                this.flabel = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.label Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.label Set end)
            }
        }
        
        /// <summary>
        /// list.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.list CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.list CustomAttributes)
        public virtual int list
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.list Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.list Get start)
                int result = this.flist;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.list Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.list Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.list Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.list Set start)
                this.flist = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.list Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.list Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec_characteristic.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.resource_spec_id CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.resource_spec_id CustomAttributes)
        [PropertyStorage(new string[] {
                "resource_spec_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.resourceSpec resource_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Get start)
                DataLine.xgvlk98.resourceSpec result = this.fresource_spec_id;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Set start)
                this.fresource_spec_id = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.resource_spec_id Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec_characteristic.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.type CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.type CustomAttributes)
        [PropertyStorage(new string[] {
                "type"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.characteristicType type
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.type Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.type Get start)
                DataLine.xgvlk98.characteristicType result = this.ftype;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.type Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.type Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.type Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.type Set end)
            }
        }
        
        /// <summary>
        /// Resource_spec_characteristic.
        /// </summary>
        //  *** Start programmer edit section *** (resourceSpecCharacteristic.dictionary_id CustomAttributes)

        //  *** End programmer edit section *** (resourceSpecCharacteristic.dictionary_id CustomAttributes)
        [PropertyStorage(new string[] {
                "dictionary_id"})]
        public virtual DataLine.xgvlk98.dictionary dictionary_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.dictionary_id Get start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.dictionary_id Get start)
                DataLine.xgvlk98.dictionary result = this.fdictionary_id;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.dictionary_id Get end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.dictionary_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.dictionary_id Set start)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.dictionary_id Set start)
                this.fdictionary_id = value;
                //  *** Start programmer edit section *** (resourceSpecCharacteristic.dictionary_id Set end)

                //  *** End programmer edit section *** (resourceSpecCharacteristic.dictionary_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "resource_spec_characteristicE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_spec_characteristicE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_spec_characteristicE", typeof(DataLine.xgvlk98.resourceSpecCharacteristic));
                }
            }
            
            /// <summary>
            /// "resource_spec_characteristicL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_spec_characteristicL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_spec_characteristicL", typeof(DataLine.xgvlk98.resourceSpecCharacteristic));
                }
            }
        }
    }
}
