//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Resource_shared.
    /// </summary>
    //  *** Start programmer edit section *** (resourceShared CustomAttributes)

    //  *** End programmer edit section *** (resourceShared CustomAttributes)
    [AutoAltered()]
    [Caption("resource_shared")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("resource_sharedE", new string[] {
            "external_id as \'External_id\'",
            "existent as \'Existent\'",
            "name as \'Name\'",
            "description as \'Description\'",
            "category as \'Category\'",
            "type as \'Type\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "customer_id as \'Customer_id\'",
            "customer_id.name"})]
    [View("resource_sharedL", new string[] {
            "external_id as \'External_id\'",
            "existent as \'Existent\'",
            "name as \'Name\'",
            "description as \'Description\'",
            "category as \'Category\'",
            "type as \'Type\'",
            "dt_created as \'Dt_created\'",
            "dt_modified as \'Dt_modified\'",
            "customer_id.name"})]
    public class resourceShared : ICSSoft.STORMNET.DataObject
    {
        
        private string fexternal_id;
        
        private bool fexistent;
        
        private string fname;
        
        private string fdescription;
        
        private string fcategory;
        
        private string ftype;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private DataLine.xgvlk98.customer fcustomer_id;
        
        //  *** Start programmer edit section *** (resourceShared CustomMembers)

        //  *** End programmer edit section *** (resourceShared CustomMembers)

        
        /// <summary>
        /// external_id.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.external_id CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.external_id CustomAttributes)
        [StrLen(128)]
        public virtual string external_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.external_id Get start)

                //  *** End programmer edit section *** (resourceShared.external_id Get start)
                string result = this.fexternal_id;
                //  *** Start programmer edit section *** (resourceShared.external_id Get end)

                //  *** End programmer edit section *** (resourceShared.external_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.external_id Set start)

                //  *** End programmer edit section *** (resourceShared.external_id Set start)
                this.fexternal_id = value;
                //  *** Start programmer edit section *** (resourceShared.external_id Set end)

                //  *** End programmer edit section *** (resourceShared.external_id Set end)
            }
        }
        
        /// <summary>
        /// existent.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.existent CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.existent CustomAttributes)
        [NotNull()]
        public virtual bool existent
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.existent Get start)

                //  *** End programmer edit section *** (resourceShared.existent Get start)
                bool result = this.fexistent;
                //  *** Start programmer edit section *** (resourceShared.existent Get end)

                //  *** End programmer edit section *** (resourceShared.existent Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.existent Set start)

                //  *** End programmer edit section *** (resourceShared.existent Set start)
                this.fexistent = value;
                //  *** Start programmer edit section *** (resourceShared.existent Set end)

                //  *** End programmer edit section *** (resourceShared.existent Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.name CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.name Get start)

                //  *** End programmer edit section *** (resourceShared.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (resourceShared.name Get end)

                //  *** End programmer edit section *** (resourceShared.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.name Set start)

                //  *** End programmer edit section *** (resourceShared.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (resourceShared.name Set end)

                //  *** End programmer edit section *** (resourceShared.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.description CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.description CustomAttributes)
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.description Get start)

                //  *** End programmer edit section *** (resourceShared.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (resourceShared.description Get end)

                //  *** End programmer edit section *** (resourceShared.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.description Set start)

                //  *** End programmer edit section *** (resourceShared.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (resourceShared.description Set end)

                //  *** End programmer edit section *** (resourceShared.description Set end)
            }
        }
        
        /// <summary>
        /// category.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.category CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.category CustomAttributes)
        [StrLen(32)]
        [NotNull()]
        public virtual string category
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.category Get start)

                //  *** End programmer edit section *** (resourceShared.category Get start)
                string result = this.fcategory;
                //  *** Start programmer edit section *** (resourceShared.category Get end)

                //  *** End programmer edit section *** (resourceShared.category Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.category Set start)

                //  *** End programmer edit section *** (resourceShared.category Set start)
                this.fcategory = value;
                //  *** Start programmer edit section *** (resourceShared.category Set end)

                //  *** End programmer edit section *** (resourceShared.category Set end)
            }
        }
        
        /// <summary>
        /// type.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.type CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.type CustomAttributes)
        [StrLen(32)]
        [NotNull()]
        public virtual string type
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.type Get start)

                //  *** End programmer edit section *** (resourceShared.type Get start)
                string result = this.ftype;
                //  *** Start programmer edit section *** (resourceShared.type Get end)

                //  *** End programmer edit section *** (resourceShared.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.type Set start)

                //  *** End programmer edit section *** (resourceShared.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (resourceShared.type Set end)

                //  *** End programmer edit section *** (resourceShared.type Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.dt_created CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.dt_created CustomAttributes)
        [NotNull()]
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.dt_created Get start)

                //  *** End programmer edit section *** (resourceShared.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (resourceShared.dt_created Get end)

                //  *** End programmer edit section *** (resourceShared.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.dt_created Set start)

                //  *** End programmer edit section *** (resourceShared.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (resourceShared.dt_created Set end)

                //  *** End programmer edit section *** (resourceShared.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.dt_modified CustomAttributes)
        [NotNull()]
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.dt_modified Get start)

                //  *** End programmer edit section *** (resourceShared.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (resourceShared.dt_modified Get end)

                //  *** End programmer edit section *** (resourceShared.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.dt_modified Set start)

                //  *** End programmer edit section *** (resourceShared.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (resourceShared.dt_modified Set end)

                //  *** End programmer edit section *** (resourceShared.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// Resource_shared.
        /// </summary>
        //  *** Start programmer edit section *** (resourceShared.customer_id CustomAttributes)

        //  *** End programmer edit section *** (resourceShared.customer_id CustomAttributes)
        [PropertyStorage(new string[] {
                "customer_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.customer customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (resourceShared.customer_id Get start)

                //  *** End programmer edit section *** (resourceShared.customer_id Get start)
                DataLine.xgvlk98.customer result = this.fcustomer_id;
                //  *** Start programmer edit section *** (resourceShared.customer_id Get end)

                //  *** End programmer edit section *** (resourceShared.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resourceShared.customer_id Set start)

                //  *** End programmer edit section *** (resourceShared.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (resourceShared.customer_id Set end)

                //  *** End programmer edit section *** (resourceShared.customer_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "resource_sharedE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_sharedE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_sharedE", typeof(DataLine.xgvlk98.resourceShared));
                }
            }
            
            /// <summary>
            /// "resource_sharedL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View resource_sharedL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("resource_sharedL", typeof(DataLine.xgvlk98.resourceShared));
                }
            }
        }
    }
}
