//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// resource_shared.
    /// </summary>
    //  *** Start programmer edit section *** (resource_shared CustomAttributes)

    //  *** End programmer edit section *** (resource_shared CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class resource_shared : ICSSoft.STORMNET.DataObject
    {
        
        private string fexternal_id;
        
        private bool fexistent;
        
        private string fname;
        
        private string fdescription;
        
        private string fcategory;
        
        private string ftype;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private DataLine.xgvlk98.customer fcustomer_id;
        
        //  *** Start programmer edit section *** (resource_shared CustomMembers)

        //  *** End programmer edit section *** (resource_shared CustomMembers)

        
        /// <summary>
        /// external_id.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.external_id CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.external_id CustomAttributes)
        [StrLen(128)]
        public virtual string external_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.external_id Get start)

                //  *** End programmer edit section *** (resource_shared.external_id Get start)
                string result = this.fexternal_id;
                //  *** Start programmer edit section *** (resource_shared.external_id Get end)

                //  *** End programmer edit section *** (resource_shared.external_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.external_id Set start)

                //  *** End programmer edit section *** (resource_shared.external_id Set start)
                this.fexternal_id = value;
                //  *** Start programmer edit section *** (resource_shared.external_id Set end)

                //  *** End programmer edit section *** (resource_shared.external_id Set end)
            }
        }
        
        /// <summary>
        /// existent.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.existent CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.existent CustomAttributes)
        public virtual bool existent
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.existent Get start)

                //  *** End programmer edit section *** (resource_shared.existent Get start)
                bool result = this.fexistent;
                //  *** Start programmer edit section *** (resource_shared.existent Get end)

                //  *** End programmer edit section *** (resource_shared.existent Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.existent Set start)

                //  *** End programmer edit section *** (resource_shared.existent Set start)
                this.fexistent = value;
                //  *** Start programmer edit section *** (resource_shared.existent Set end)

                //  *** End programmer edit section *** (resource_shared.existent Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.name CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.name Get start)

                //  *** End programmer edit section *** (resource_shared.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (resource_shared.name Get end)

                //  *** End programmer edit section *** (resource_shared.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.name Set start)

                //  *** End programmer edit section *** (resource_shared.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (resource_shared.name Set end)

                //  *** End programmer edit section *** (resource_shared.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.description CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.description CustomAttributes)
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.description Get start)

                //  *** End programmer edit section *** (resource_shared.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (resource_shared.description Get end)

                //  *** End programmer edit section *** (resource_shared.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.description Set start)

                //  *** End programmer edit section *** (resource_shared.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (resource_shared.description Set end)

                //  *** End programmer edit section *** (resource_shared.description Set end)
            }
        }
        
        /// <summary>
        /// category.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.category CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.category CustomAttributes)
        [StrLen(32)]
        public virtual string category
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.category Get start)

                //  *** End programmer edit section *** (resource_shared.category Get start)
                string result = this.fcategory;
                //  *** Start programmer edit section *** (resource_shared.category Get end)

                //  *** End programmer edit section *** (resource_shared.category Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.category Set start)

                //  *** End programmer edit section *** (resource_shared.category Set start)
                this.fcategory = value;
                //  *** Start programmer edit section *** (resource_shared.category Set end)

                //  *** End programmer edit section *** (resource_shared.category Set end)
            }
        }
        
        /// <summary>
        /// type.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.type CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.type CustomAttributes)
        [StrLen(32)]
        public virtual string type
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.type Get start)

                //  *** End programmer edit section *** (resource_shared.type Get start)
                string result = this.ftype;
                //  *** Start programmer edit section *** (resource_shared.type Get end)

                //  *** End programmer edit section *** (resource_shared.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.type Set start)

                //  *** End programmer edit section *** (resource_shared.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (resource_shared.type Set end)

                //  *** End programmer edit section *** (resource_shared.type Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.dt_created CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.dt_created CustomAttributes)
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.dt_created Get start)

                //  *** End programmer edit section *** (resource_shared.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (resource_shared.dt_created Get end)

                //  *** End programmer edit section *** (resource_shared.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.dt_created Set start)

                //  *** End programmer edit section *** (resource_shared.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (resource_shared.dt_created Set end)

                //  *** End programmer edit section *** (resource_shared.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.dt_modified CustomAttributes)
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.dt_modified Get start)

                //  *** End programmer edit section *** (resource_shared.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (resource_shared.dt_modified Get end)

                //  *** End programmer edit section *** (resource_shared.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.dt_modified Set start)

                //  *** End programmer edit section *** (resource_shared.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (resource_shared.dt_modified Set end)

                //  *** End programmer edit section *** (resource_shared.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// resource_shared.
        /// </summary>
        //  *** Start programmer edit section *** (resource_shared.customer_id CustomAttributes)

        //  *** End programmer edit section *** (resource_shared.customer_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.xgvlk98.customer customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (resource_shared.customer_id Get start)

                //  *** End programmer edit section *** (resource_shared.customer_id Get start)
                DataLine.xgvlk98.customer result = this.fcustomer_id;
                //  *** Start programmer edit section *** (resource_shared.customer_id Get end)

                //  *** End programmer edit section *** (resource_shared.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (resource_shared.customer_id Set start)

                //  *** End programmer edit section *** (resource_shared.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (resource_shared.customer_id Set end)

                //  *** End programmer edit section *** (resource_shared.customer_id Set end)
            }
        }
    }
}
