//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// service_state.
    /// </summary>
    //  *** Start programmer edit section *** (service_state CustomAttributes)

    //  *** End programmer edit section *** (service_state CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class service_state : ICSSoft.STORMNET.DataObject
    {
        
        private string fdescription;
        
        //  *** Start programmer edit section *** (service_state CustomMembers)

        //  *** End programmer edit section *** (service_state CustomMembers)

        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (service_state.description CustomAttributes)

        //  *** End programmer edit section *** (service_state.description CustomAttributes)
        [StrLen(255)]
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (service_state.description Get start)

                //  *** End programmer edit section *** (service_state.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (service_state.description Get end)

                //  *** End programmer edit section *** (service_state.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_state.description Set start)

                //  *** End programmer edit section *** (service_state.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (service_state.description Set end)

                //  *** End programmer edit section *** (service_state.description Set end)
            }
        }
    }
}
