//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// service_order.
    /// </summary>
    //  *** Start programmer edit section *** (service_order CustomAttributes)

    //  *** End programmer edit section *** (service_order CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class service_order : ICSSoft.STORMNET.DataObject
    {
        
        private string fdescription;
        
        private System.DateTime fdt_completed;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_modified;
        
        private System.DateTime fdt_started;
        
        private System.Guid fexternal_id;
        
        private double fprice;
        
        private DataLine.xgvlk98.contragent fcontragent_id;
        
        private DataLine.xgvlk98.usr fcreator_id;
        
        private DataLine.xgvlk98.usr fmodifier_id;
        
        //  *** Start programmer edit section *** (service_order CustomMembers)

        //  *** End programmer edit section *** (service_order CustomMembers)

        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.description CustomAttributes)

        //  *** End programmer edit section *** (service_order.description CustomAttributes)
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.description Get start)

                //  *** End programmer edit section *** (service_order.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (service_order.description Get end)

                //  *** End programmer edit section *** (service_order.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.description Set start)

                //  *** End programmer edit section *** (service_order.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (service_order.description Set end)

                //  *** End programmer edit section *** (service_order.description Set end)
            }
        }
        
        /// <summary>
        /// dt_completed.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.dt_completed CustomAttributes)

        //  *** End programmer edit section *** (service_order.dt_completed CustomAttributes)
        public virtual System.DateTime dt_completed
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.dt_completed Get start)

                //  *** End programmer edit section *** (service_order.dt_completed Get start)
                System.DateTime result = this.fdt_completed;
                //  *** Start programmer edit section *** (service_order.dt_completed Get end)

                //  *** End programmer edit section *** (service_order.dt_completed Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.dt_completed Set start)

                //  *** End programmer edit section *** (service_order.dt_completed Set start)
                this.fdt_completed = value;
                //  *** Start programmer edit section *** (service_order.dt_completed Set end)

                //  *** End programmer edit section *** (service_order.dt_completed Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.dt_created CustomAttributes)

        //  *** End programmer edit section *** (service_order.dt_created CustomAttributes)
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.dt_created Get start)

                //  *** End programmer edit section *** (service_order.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (service_order.dt_created Get end)

                //  *** End programmer edit section *** (service_order.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.dt_created Set start)

                //  *** End programmer edit section *** (service_order.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (service_order.dt_created Set end)

                //  *** End programmer edit section *** (service_order.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_modified.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.dt_modified CustomAttributes)

        //  *** End programmer edit section *** (service_order.dt_modified CustomAttributes)
        public virtual System.DateTime dt_modified
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.dt_modified Get start)

                //  *** End programmer edit section *** (service_order.dt_modified Get start)
                System.DateTime result = this.fdt_modified;
                //  *** Start programmer edit section *** (service_order.dt_modified Get end)

                //  *** End programmer edit section *** (service_order.dt_modified Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.dt_modified Set start)

                //  *** End programmer edit section *** (service_order.dt_modified Set start)
                this.fdt_modified = value;
                //  *** Start programmer edit section *** (service_order.dt_modified Set end)

                //  *** End programmer edit section *** (service_order.dt_modified Set end)
            }
        }
        
        /// <summary>
        /// dt_started.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.dt_started CustomAttributes)

        //  *** End programmer edit section *** (service_order.dt_started CustomAttributes)
        public virtual System.DateTime dt_started
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.dt_started Get start)

                //  *** End programmer edit section *** (service_order.dt_started Get start)
                System.DateTime result = this.fdt_started;
                //  *** Start programmer edit section *** (service_order.dt_started Get end)

                //  *** End programmer edit section *** (service_order.dt_started Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.dt_started Set start)

                //  *** End programmer edit section *** (service_order.dt_started Set start)
                this.fdt_started = value;
                //  *** Start programmer edit section *** (service_order.dt_started Set end)

                //  *** End programmer edit section *** (service_order.dt_started Set end)
            }
        }
        
        /// <summary>
        /// external_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.external_id CustomAttributes)

        //  *** End programmer edit section *** (service_order.external_id CustomAttributes)
        public virtual System.Guid external_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.external_id Get start)

                //  *** End programmer edit section *** (service_order.external_id Get start)
                System.Guid result = this.fexternal_id;
                //  *** Start programmer edit section *** (service_order.external_id Get end)

                //  *** End programmer edit section *** (service_order.external_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.external_id Set start)

                //  *** End programmer edit section *** (service_order.external_id Set start)
                this.fexternal_id = value;
                //  *** Start programmer edit section *** (service_order.external_id Set end)

                //  *** End programmer edit section *** (service_order.external_id Set end)
            }
        }
        
        /// <summary>
        /// price.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.price CustomAttributes)

        //  *** End programmer edit section *** (service_order.price CustomAttributes)
        public virtual double price
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.price Get start)

                //  *** End programmer edit section *** (service_order.price Get start)
                double result = this.fprice;
                //  *** Start programmer edit section *** (service_order.price Get end)

                //  *** End programmer edit section *** (service_order.price Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.price Set start)

                //  *** End programmer edit section *** (service_order.price Set start)
                this.fprice = value;
                //  *** Start programmer edit section *** (service_order.price Set end)

                //  *** End programmer edit section *** (service_order.price Set end)
            }
        }
        
        /// <summary>
        /// service_order.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.contragent_id CustomAttributes)

        //  *** End programmer edit section *** (service_order.contragent_id CustomAttributes)
        public virtual DataLine.xgvlk98.contragent contragent_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.contragent_id Get start)

                //  *** End programmer edit section *** (service_order.contragent_id Get start)
                DataLine.xgvlk98.contragent result = this.fcontragent_id;
                //  *** Start programmer edit section *** (service_order.contragent_id Get end)

                //  *** End programmer edit section *** (service_order.contragent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.contragent_id Set start)

                //  *** End programmer edit section *** (service_order.contragent_id Set start)
                this.fcontragent_id = value;
                //  *** Start programmer edit section *** (service_order.contragent_id Set end)

                //  *** End programmer edit section *** (service_order.contragent_id Set end)
            }
        }
        
        /// <summary>
        /// service_order.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.creator_id CustomAttributes)

        //  *** End programmer edit section *** (service_order.creator_id CustomAttributes)
        public virtual DataLine.xgvlk98.usr creator_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.creator_id Get start)

                //  *** End programmer edit section *** (service_order.creator_id Get start)
                DataLine.xgvlk98.usr result = this.fcreator_id;
                //  *** Start programmer edit section *** (service_order.creator_id Get end)

                //  *** End programmer edit section *** (service_order.creator_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.creator_id Set start)

                //  *** End programmer edit section *** (service_order.creator_id Set start)
                this.fcreator_id = value;
                //  *** Start programmer edit section *** (service_order.creator_id Set end)

                //  *** End programmer edit section *** (service_order.creator_id Set end)
            }
        }
        
        /// <summary>
        /// service_order.
        /// </summary>
        //  *** Start programmer edit section *** (service_order.modifier_id CustomAttributes)

        //  *** End programmer edit section *** (service_order.modifier_id CustomAttributes)
        public virtual DataLine.xgvlk98.usr modifier_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_order.modifier_id Get start)

                //  *** End programmer edit section *** (service_order.modifier_id Get start)
                DataLine.xgvlk98.usr result = this.fmodifier_id;
                //  *** Start programmer edit section *** (service_order.modifier_id Get end)

                //  *** End programmer edit section *** (service_order.modifier_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_order.modifier_id Set start)

                //  *** End programmer edit section *** (service_order.modifier_id Set start)
                this.fmodifier_id = value;
                //  *** Start programmer edit section *** (service_order.modifier_id Set end)

                //  *** End programmer edit section *** (service_order.modifier_id Set end)
            }
        }
    }
}
