//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Service_usage_spec.
    /// </summary>
    //  *** Start programmer edit section *** (serviceUsageSpec CustomAttributes)

    //  *** End programmer edit section *** (serviceUsageSpec CustomAttributes)
    [AutoAltered()]
    [Caption("service_usage_spec")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("service_usage_specE", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "map as \'Map\'",
            "unit as \'Unit\'",
            "type as \'Type\'",
            "type.regex as \'Regex\'",
            "service_spec_id as \'Service_spec_id\'",
            "service_spec_id.enum as \'Enum\'"})]
    [View("service_usage_specL", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "map as \'Map\'",
            "unit as \'Unit\'",
            "type.regex as \'Regex\'",
            "service_spec_id.enum as \'Enum\'"})]
    public class serviceUsageSpec : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fvalue;
        
        private bool fmap;
        
        private string funit;
        
        private DataLine.xgvlk98.serviceSpec fservice_spec_id;
        
        private DataLine.xgvlk98.characteristicType ftype;
        
        //  *** Start programmer edit section *** (serviceUsageSpec CustomMembers)

        //  *** End programmer edit section *** (serviceUsageSpec CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (serviceUsageSpec.name CustomAttributes)

        //  *** End programmer edit section *** (serviceUsageSpec.name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.name Get start)

                //  *** End programmer edit section *** (serviceUsageSpec.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (serviceUsageSpec.name Get end)

                //  *** End programmer edit section *** (serviceUsageSpec.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.name Set start)

                //  *** End programmer edit section *** (serviceUsageSpec.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (serviceUsageSpec.name Set end)

                //  *** End programmer edit section *** (serviceUsageSpec.name Set end)
            }
        }
        
        /// <summary>
        /// value.
        /// </summary>
        //  *** Start programmer edit section *** (serviceUsageSpec.value CustomAttributes)

        //  *** End programmer edit section *** (serviceUsageSpec.value CustomAttributes)
        [StrLen(255)]
        public virtual string value
        {
            get
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.value Get start)

                //  *** End programmer edit section *** (serviceUsageSpec.value Get start)
                string result = this.fvalue;
                //  *** Start programmer edit section *** (serviceUsageSpec.value Get end)

                //  *** End programmer edit section *** (serviceUsageSpec.value Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.value Set start)

                //  *** End programmer edit section *** (serviceUsageSpec.value Set start)
                this.fvalue = value;
                //  *** Start programmer edit section *** (serviceUsageSpec.value Set end)

                //  *** End programmer edit section *** (serviceUsageSpec.value Set end)
            }
        }
        
        /// <summary>
        /// map.
        /// </summary>
        //  *** Start programmer edit section *** (serviceUsageSpec.map CustomAttributes)

        //  *** End programmer edit section *** (serviceUsageSpec.map CustomAttributes)
        [NotNull()]
        public virtual bool map
        {
            get
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.map Get start)

                //  *** End programmer edit section *** (serviceUsageSpec.map Get start)
                bool result = this.fmap;
                //  *** Start programmer edit section *** (serviceUsageSpec.map Get end)

                //  *** End programmer edit section *** (serviceUsageSpec.map Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.map Set start)

                //  *** End programmer edit section *** (serviceUsageSpec.map Set start)
                this.fmap = value;
                //  *** Start programmer edit section *** (serviceUsageSpec.map Set end)

                //  *** End programmer edit section *** (serviceUsageSpec.map Set end)
            }
        }
        
        /// <summary>
        /// unit.
        /// </summary>
        //  *** Start programmer edit section *** (serviceUsageSpec.unit CustomAttributes)

        //  *** End programmer edit section *** (serviceUsageSpec.unit CustomAttributes)
        [StrLen(32)]
        public virtual string unit
        {
            get
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.unit Get start)

                //  *** End programmer edit section *** (serviceUsageSpec.unit Get start)
                string result = this.funit;
                //  *** Start programmer edit section *** (serviceUsageSpec.unit Get end)

                //  *** End programmer edit section *** (serviceUsageSpec.unit Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.unit Set start)

                //  *** End programmer edit section *** (serviceUsageSpec.unit Set start)
                this.funit = value;
                //  *** Start programmer edit section *** (serviceUsageSpec.unit Set end)

                //  *** End programmer edit section *** (serviceUsageSpec.unit Set end)
            }
        }
        
        /// <summary>
        /// Service_usage_spec.
        /// </summary>
        //  *** Start programmer edit section *** (serviceUsageSpec.service_spec_id CustomAttributes)

        //  *** End programmer edit section *** (serviceUsageSpec.service_spec_id CustomAttributes)
        [PropertyStorage(new string[] {
                "service_spec_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.serviceSpec service_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.service_spec_id Get start)

                //  *** End programmer edit section *** (serviceUsageSpec.service_spec_id Get start)
                DataLine.xgvlk98.serviceSpec result = this.fservice_spec_id;
                //  *** Start programmer edit section *** (serviceUsageSpec.service_spec_id Get end)

                //  *** End programmer edit section *** (serviceUsageSpec.service_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.service_spec_id Set start)

                //  *** End programmer edit section *** (serviceUsageSpec.service_spec_id Set start)
                this.fservice_spec_id = value;
                //  *** Start programmer edit section *** (serviceUsageSpec.service_spec_id Set end)

                //  *** End programmer edit section *** (serviceUsageSpec.service_spec_id Set end)
            }
        }
        
        /// <summary>
        /// Service_usage_spec.
        /// </summary>
        //  *** Start programmer edit section *** (serviceUsageSpec.type CustomAttributes)

        //  *** End programmer edit section *** (serviceUsageSpec.type CustomAttributes)
        [PropertyStorage(new string[] {
                "type"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.characteristicType type
        {
            get
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.type Get start)

                //  *** End programmer edit section *** (serviceUsageSpec.type Get start)
                DataLine.xgvlk98.characteristicType result = this.ftype;
                //  *** Start programmer edit section *** (serviceUsageSpec.type Get end)

                //  *** End programmer edit section *** (serviceUsageSpec.type Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceUsageSpec.type Set start)

                //  *** End programmer edit section *** (serviceUsageSpec.type Set start)
                this.ftype = value;
                //  *** Start programmer edit section *** (serviceUsageSpec.type Set end)

                //  *** End programmer edit section *** (serviceUsageSpec.type Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "service_usage_specE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View service_usage_specE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("service_usage_specE", typeof(DataLine.xgvlk98.serviceUsageSpec));
                }
            }
            
            /// <summary>
            /// "service_usage_specL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View service_usage_specL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("service_usage_specL", typeof(DataLine.xgvlk98.serviceUsageSpec));
                }
            }
        }
    }
}
