//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Service_characteristic.
    /// </summary>
    //  *** Start programmer edit section *** (serviceCharacteristic CustomAttributes)

    //  *** End programmer edit section *** (serviceCharacteristic CustomAttributes)
    [AutoAltered()]
    [Caption("service_characteristic")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("service_characteristicE", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "service_id as \'Service_id\'",
            "service_id.name as \'Name\'",
            "service_id as \'Service_id\'",
            "service_id.name as \'Name\'"})]
    [View("service_characteristicL", new string[] {
            "name as \'Name\'",
            "value as \'Value\'",
            "service_id.name as \'Name\'",
            "service_id.name as \'Name\'"})]
    public class serviceCharacteristic : ICSSoft.STORMNET.DataObject
    {
        
        private string fname;
        
        private string fvalue;
        
        private DataLine.xgvlk98.service fservice_id;
        
        //  *** Start programmer edit section *** (serviceCharacteristic CustomMembers)

        //  *** End programmer edit section *** (serviceCharacteristic CustomMembers)

        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (serviceCharacteristic.name CustomAttributes)

        //  *** End programmer edit section *** (serviceCharacteristic.name CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (serviceCharacteristic.name Get start)

                //  *** End programmer edit section *** (serviceCharacteristic.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (serviceCharacteristic.name Get end)

                //  *** End programmer edit section *** (serviceCharacteristic.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceCharacteristic.name Set start)

                //  *** End programmer edit section *** (serviceCharacteristic.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (serviceCharacteristic.name Set end)

                //  *** End programmer edit section *** (serviceCharacteristic.name Set end)
            }
        }
        
        /// <summary>
        /// value.
        /// </summary>
        //  *** Start programmer edit section *** (serviceCharacteristic.value CustomAttributes)

        //  *** End programmer edit section *** (serviceCharacteristic.value CustomAttributes)
        [StrLen(255)]
        public virtual string value
        {
            get
            {
                //  *** Start programmer edit section *** (serviceCharacteristic.value Get start)

                //  *** End programmer edit section *** (serviceCharacteristic.value Get start)
                string result = this.fvalue;
                //  *** Start programmer edit section *** (serviceCharacteristic.value Get end)

                //  *** End programmer edit section *** (serviceCharacteristic.value Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceCharacteristic.value Set start)

                //  *** End programmer edit section *** (serviceCharacteristic.value Set start)
                this.fvalue = value;
                //  *** Start programmer edit section *** (serviceCharacteristic.value Set end)

                //  *** End programmer edit section *** (serviceCharacteristic.value Set end)
            }
        }
        
        /// <summary>
        /// Service_characteristic.
        /// </summary>
        //  *** Start programmer edit section *** (serviceCharacteristic.service_id CustomAttributes)

        //  *** End programmer edit section *** (serviceCharacteristic.service_id CustomAttributes)
        [PropertyStorage(new string[] {
                "service_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.service service_id
        {
            get
            {
                //  *** Start programmer edit section *** (serviceCharacteristic.service_id Get start)

                //  *** End programmer edit section *** (serviceCharacteristic.service_id Get start)
                DataLine.xgvlk98.service result = this.fservice_id;
                //  *** Start programmer edit section *** (serviceCharacteristic.service_id Get end)

                //  *** End programmer edit section *** (serviceCharacteristic.service_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (serviceCharacteristic.service_id Set start)

                //  *** End programmer edit section *** (serviceCharacteristic.service_id Set start)
                this.fservice_id = value;
                //  *** Start programmer edit section *** (serviceCharacteristic.service_id Set end)

                //  *** End programmer edit section *** (serviceCharacteristic.service_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "service_characteristicE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View service_characteristicE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("service_characteristicE", typeof(DataLine.xgvlk98.serviceCharacteristic));
                }
            }
            
            /// <summary>
            /// "service_characteristicL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View service_characteristicL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("service_characteristicL", typeof(DataLine.xgvlk98.serviceCharacteristic));
                }
            }
        }
    }
}
