//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// service_log.
    /// </summary>
    //  *** Start programmer edit section *** (service_log CustomAttributes)

    //  *** End programmer edit section *** (service_log CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class service_log : ICSSoft.STORMNET.DataObject
    {
        
        private int fservice_id;
        
        private int fcfs_id;
        
        private int fparent_id;
        
        private int fcontragent_id;
        
        private int fcustomer_id;
        
        private int fservice_spec_id;
        
        private string fstate;
        
        private string fname;
        
        private string fdescription;
        
        private System.DateTime fdt_created;
        
        private System.DateTime fdt_started;
        
        private System.DateTime fdt_ended;
        
        private System.DateTime fstart_time;
        
        private System.DateTime fend_time;
        
        //  *** Start programmer edit section *** (service_log CustomMembers)

        //  *** End programmer edit section *** (service_log CustomMembers)

        
        /// <summary>
        /// service_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.service_id CustomAttributes)

        //  *** End programmer edit section *** (service_log.service_id CustomAttributes)
        public virtual int service_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.service_id Get start)

                //  *** End programmer edit section *** (service_log.service_id Get start)
                int result = this.fservice_id;
                //  *** Start programmer edit section *** (service_log.service_id Get end)

                //  *** End programmer edit section *** (service_log.service_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.service_id Set start)

                //  *** End programmer edit section *** (service_log.service_id Set start)
                this.fservice_id = value;
                //  *** Start programmer edit section *** (service_log.service_id Set end)

                //  *** End programmer edit section *** (service_log.service_id Set end)
            }
        }
        
        /// <summary>
        /// cfs_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.cfs_id CustomAttributes)

        //  *** End programmer edit section *** (service_log.cfs_id CustomAttributes)
        public virtual int cfs_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.cfs_id Get start)

                //  *** End programmer edit section *** (service_log.cfs_id Get start)
                int result = this.fcfs_id;
                //  *** Start programmer edit section *** (service_log.cfs_id Get end)

                //  *** End programmer edit section *** (service_log.cfs_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.cfs_id Set start)

                //  *** End programmer edit section *** (service_log.cfs_id Set start)
                this.fcfs_id = value;
                //  *** Start programmer edit section *** (service_log.cfs_id Set end)

                //  *** End programmer edit section *** (service_log.cfs_id Set end)
            }
        }
        
        /// <summary>
        /// parent_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.parent_id CustomAttributes)

        //  *** End programmer edit section *** (service_log.parent_id CustomAttributes)
        public virtual int parent_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.parent_id Get start)

                //  *** End programmer edit section *** (service_log.parent_id Get start)
                int result = this.fparent_id;
                //  *** Start programmer edit section *** (service_log.parent_id Get end)

                //  *** End programmer edit section *** (service_log.parent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.parent_id Set start)

                //  *** End programmer edit section *** (service_log.parent_id Set start)
                this.fparent_id = value;
                //  *** Start programmer edit section *** (service_log.parent_id Set end)

                //  *** End programmer edit section *** (service_log.parent_id Set end)
            }
        }
        
        /// <summary>
        /// contragent_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.contragent_id CustomAttributes)

        //  *** End programmer edit section *** (service_log.contragent_id CustomAttributes)
        public virtual int contragent_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.contragent_id Get start)

                //  *** End programmer edit section *** (service_log.contragent_id Get start)
                int result = this.fcontragent_id;
                //  *** Start programmer edit section *** (service_log.contragent_id Get end)

                //  *** End programmer edit section *** (service_log.contragent_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.contragent_id Set start)

                //  *** End programmer edit section *** (service_log.contragent_id Set start)
                this.fcontragent_id = value;
                //  *** Start programmer edit section *** (service_log.contragent_id Set end)

                //  *** End programmer edit section *** (service_log.contragent_id Set end)
            }
        }
        
        /// <summary>
        /// customer_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.customer_id CustomAttributes)

        //  *** End programmer edit section *** (service_log.customer_id CustomAttributes)
        public virtual int customer_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.customer_id Get start)

                //  *** End programmer edit section *** (service_log.customer_id Get start)
                int result = this.fcustomer_id;
                //  *** Start programmer edit section *** (service_log.customer_id Get end)

                //  *** End programmer edit section *** (service_log.customer_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.customer_id Set start)

                //  *** End programmer edit section *** (service_log.customer_id Set start)
                this.fcustomer_id = value;
                //  *** Start programmer edit section *** (service_log.customer_id Set end)

                //  *** End programmer edit section *** (service_log.customer_id Set end)
            }
        }
        
        /// <summary>
        /// service_spec_id.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.service_spec_id CustomAttributes)

        //  *** End programmer edit section *** (service_log.service_spec_id CustomAttributes)
        public virtual int service_spec_id
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.service_spec_id Get start)

                //  *** End programmer edit section *** (service_log.service_spec_id Get start)
                int result = this.fservice_spec_id;
                //  *** Start programmer edit section *** (service_log.service_spec_id Get end)

                //  *** End programmer edit section *** (service_log.service_spec_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.service_spec_id Set start)

                //  *** End programmer edit section *** (service_log.service_spec_id Set start)
                this.fservice_spec_id = value;
                //  *** Start programmer edit section *** (service_log.service_spec_id Set end)

                //  *** End programmer edit section *** (service_log.service_spec_id Set end)
            }
        }
        
        /// <summary>
        /// state.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.state CustomAttributes)

        //  *** End programmer edit section *** (service_log.state CustomAttributes)
        [StrLen(32)]
        public virtual string state
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.state Get start)

                //  *** End programmer edit section *** (service_log.state Get start)
                string result = this.fstate;
                //  *** Start programmer edit section *** (service_log.state Get end)

                //  *** End programmer edit section *** (service_log.state Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.state Set start)

                //  *** End programmer edit section *** (service_log.state Set start)
                this.fstate = value;
                //  *** Start programmer edit section *** (service_log.state Set end)

                //  *** End programmer edit section *** (service_log.state Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.name CustomAttributes)

        //  *** End programmer edit section *** (service_log.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.name Get start)

                //  *** End programmer edit section *** (service_log.name Get start)
                string result = this.fname;
                //  *** Start programmer edit section *** (service_log.name Get end)

                //  *** End programmer edit section *** (service_log.name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.name Set start)

                //  *** End programmer edit section *** (service_log.name Set start)
                this.fname = value;
                //  *** Start programmer edit section *** (service_log.name Set end)

                //  *** End programmer edit section *** (service_log.name Set end)
            }
        }
        
        /// <summary>
        /// description.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.description CustomAttributes)

        //  *** End programmer edit section *** (service_log.description CustomAttributes)
        public virtual string description
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.description Get start)

                //  *** End programmer edit section *** (service_log.description Get start)
                string result = this.fdescription;
                //  *** Start programmer edit section *** (service_log.description Get end)

                //  *** End programmer edit section *** (service_log.description Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.description Set start)

                //  *** End programmer edit section *** (service_log.description Set start)
                this.fdescription = value;
                //  *** Start programmer edit section *** (service_log.description Set end)

                //  *** End programmer edit section *** (service_log.description Set end)
            }
        }
        
        /// <summary>
        /// dt_created.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.dt_created CustomAttributes)

        //  *** End programmer edit section *** (service_log.dt_created CustomAttributes)
        public virtual System.DateTime dt_created
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.dt_created Get start)

                //  *** End programmer edit section *** (service_log.dt_created Get start)
                System.DateTime result = this.fdt_created;
                //  *** Start programmer edit section *** (service_log.dt_created Get end)

                //  *** End programmer edit section *** (service_log.dt_created Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.dt_created Set start)

                //  *** End programmer edit section *** (service_log.dt_created Set start)
                this.fdt_created = value;
                //  *** Start programmer edit section *** (service_log.dt_created Set end)

                //  *** End programmer edit section *** (service_log.dt_created Set end)
            }
        }
        
        /// <summary>
        /// dt_started.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.dt_started CustomAttributes)

        //  *** End programmer edit section *** (service_log.dt_started CustomAttributes)
        public virtual System.DateTime dt_started
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.dt_started Get start)

                //  *** End programmer edit section *** (service_log.dt_started Get start)
                System.DateTime result = this.fdt_started;
                //  *** Start programmer edit section *** (service_log.dt_started Get end)

                //  *** End programmer edit section *** (service_log.dt_started Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.dt_started Set start)

                //  *** End programmer edit section *** (service_log.dt_started Set start)
                this.fdt_started = value;
                //  *** Start programmer edit section *** (service_log.dt_started Set end)

                //  *** End programmer edit section *** (service_log.dt_started Set end)
            }
        }
        
        /// <summary>
        /// dt_ended.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.dt_ended CustomAttributes)

        //  *** End programmer edit section *** (service_log.dt_ended CustomAttributes)
        public virtual System.DateTime dt_ended
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.dt_ended Get start)

                //  *** End programmer edit section *** (service_log.dt_ended Get start)
                System.DateTime result = this.fdt_ended;
                //  *** Start programmer edit section *** (service_log.dt_ended Get end)

                //  *** End programmer edit section *** (service_log.dt_ended Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.dt_ended Set start)

                //  *** End programmer edit section *** (service_log.dt_ended Set start)
                this.fdt_ended = value;
                //  *** Start programmer edit section *** (service_log.dt_ended Set end)

                //  *** End programmer edit section *** (service_log.dt_ended Set end)
            }
        }
        
        /// <summary>
        /// start_time.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.start_time CustomAttributes)

        //  *** End programmer edit section *** (service_log.start_time CustomAttributes)
        public virtual System.DateTime start_time
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.start_time Get start)

                //  *** End programmer edit section *** (service_log.start_time Get start)
                System.DateTime result = this.fstart_time;
                //  *** Start programmer edit section *** (service_log.start_time Get end)

                //  *** End programmer edit section *** (service_log.start_time Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.start_time Set start)

                //  *** End programmer edit section *** (service_log.start_time Set start)
                this.fstart_time = value;
                //  *** Start programmer edit section *** (service_log.start_time Set end)

                //  *** End programmer edit section *** (service_log.start_time Set end)
            }
        }
        
        /// <summary>
        /// end_time.
        /// </summary>
        //  *** Start programmer edit section *** (service_log.end_time CustomAttributes)

        //  *** End programmer edit section *** (service_log.end_time CustomAttributes)
        public virtual System.DateTime end_time
        {
            get
            {
                //  *** Start programmer edit section *** (service_log.end_time Get start)

                //  *** End programmer edit section *** (service_log.end_time Get start)
                System.DateTime result = this.fend_time;
                //  *** Start programmer edit section *** (service_log.end_time Get end)

                //  *** End programmer edit section *** (service_log.end_time Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (service_log.end_time Set start)

                //  *** End programmer edit section *** (service_log.end_time Set start)
                this.fend_time = value;
                //  *** Start programmer edit section *** (service_log.end_time Set end)

                //  *** End programmer edit section *** (service_log.end_time Set end)
            }
        }
    }
}
