//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User_group.
    /// </summary>
    //  *** Start programmer edit section *** (userGroup CustomAttributes)

    //  *** End programmer edit section *** (userGroup CustomAttributes)
    [AutoAltered()]
    [Caption("user_group")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("user_groupE", new string[] {
            "user_id as \'User_id\'",
            "user_id.login as \'Login\'",
            "group_id as \'Group_id\'",
            "group_id.name as \'Name\'"})]
    [View("user_groupL", new string[] {
            "user_id.login as \'Login\'",
            "group_id.name as \'Name\'"})]
    public class userGroup : ICSSoft.STORMNET.DataObject
    {
        
        private DataLine.xgvlk98.grp fgroup_id;
        
        private DataLine.xgvlk98.usr fuser_id;
        
        //  *** Start programmer edit section *** (userGroup CustomMembers)

        //  *** End programmer edit section *** (userGroup CustomMembers)

        
        /// <summary>
        /// User_group.
        /// </summary>
        //  *** Start programmer edit section *** (userGroup.group_id CustomAttributes)

        //  *** End programmer edit section *** (userGroup.group_id CustomAttributes)
        [PropertyStorage(new string[] {
                "group_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.grp group_id
        {
            get
            {
                //  *** Start programmer edit section *** (userGroup.group_id Get start)

                //  *** End programmer edit section *** (userGroup.group_id Get start)
                DataLine.xgvlk98.grp result = this.fgroup_id;
                //  *** Start programmer edit section *** (userGroup.group_id Get end)

                //  *** End programmer edit section *** (userGroup.group_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (userGroup.group_id Set start)

                //  *** End programmer edit section *** (userGroup.group_id Set start)
                this.fgroup_id = value;
                //  *** Start programmer edit section *** (userGroup.group_id Set end)

                //  *** End programmer edit section *** (userGroup.group_id Set end)
            }
        }
        
        /// <summary>
        /// User_group.
        /// </summary>
        //  *** Start programmer edit section *** (userGroup.user_id CustomAttributes)

        //  *** End programmer edit section *** (userGroup.user_id CustomAttributes)
        [PropertyStorage(new string[] {
                "user_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.usr user_id
        {
            get
            {
                //  *** Start programmer edit section *** (userGroup.user_id Get start)

                //  *** End programmer edit section *** (userGroup.user_id Get start)
                DataLine.xgvlk98.usr result = this.fuser_id;
                //  *** Start programmer edit section *** (userGroup.user_id Get end)

                //  *** End programmer edit section *** (userGroup.user_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (userGroup.user_id Set start)

                //  *** End programmer edit section *** (userGroup.user_id Set start)
                this.fuser_id = value;
                //  *** Start programmer edit section *** (userGroup.user_id Set end)

                //  *** End programmer edit section *** (userGroup.user_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "user_groupE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View user_groupE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("user_groupE", typeof(DataLine.xgvlk98.userGroup));
                }
            }
            
            /// <summary>
            /// "user_groupL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View user_groupL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("user_groupL", typeof(DataLine.xgvlk98.userGroup));
                }
            }
        }
    }
}
