//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User_service_order.
    /// </summary>
    //  *** Start programmer edit section *** (userServiceOrder CustomAttributes)

    //  *** End programmer edit section *** (userServiceOrder CustomAttributes)
    [AutoAltered()]
    [Caption("user_service_order")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("user_service_orderE", new string[] {
            "action as \'Action\'",
            "dt_action as \'Dt_action\'",
            "user_id as \'User_id\'",
            "user_id.login as \'Login\'",
            "service_order_id as \'Service_order_id\'",
            "service_order_id.description as \'Description\'"})]
    [View("user_service_orderL", new string[] {
            "action as \'Action\'",
            "dt_action as \'Dt_action\'",
            "user_id.login as \'Login\'",
            "service_order_id.description as \'Description\'"})]
    public class userServiceOrder : ICSSoft.STORMNET.DataObject
    {
        
        private string faction;
        
        private System.DateTime fdt_action;
        
        private DataLine.xgvlk98.serviceOrder fservice_order_id;
        
        private DataLine.xgvlk98.usr fuser_id;
        
        //  *** Start programmer edit section *** (userServiceOrder CustomMembers)

        //  *** End programmer edit section *** (userServiceOrder CustomMembers)

        
        /// <summary>
        /// action.
        /// </summary>
        //  *** Start programmer edit section *** (userServiceOrder.action CustomAttributes)

        //  *** End programmer edit section *** (userServiceOrder.action CustomAttributes)
        [StrLen(32)]
        [NotNull()]
        public virtual string action
        {
            get
            {
                //  *** Start programmer edit section *** (userServiceOrder.action Get start)

                //  *** End programmer edit section *** (userServiceOrder.action Get start)
                string result = this.faction;
                //  *** Start programmer edit section *** (userServiceOrder.action Get end)

                //  *** End programmer edit section *** (userServiceOrder.action Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (userServiceOrder.action Set start)

                //  *** End programmer edit section *** (userServiceOrder.action Set start)
                this.faction = value;
                //  *** Start programmer edit section *** (userServiceOrder.action Set end)

                //  *** End programmer edit section *** (userServiceOrder.action Set end)
            }
        }
        
        /// <summary>
        /// dt_action.
        /// </summary>
        //  *** Start programmer edit section *** (userServiceOrder.dt_action CustomAttributes)

        //  *** End programmer edit section *** (userServiceOrder.dt_action CustomAttributes)
        [NotNull()]
        public virtual System.DateTime dt_action
        {
            get
            {
                //  *** Start programmer edit section *** (userServiceOrder.dt_action Get start)

                //  *** End programmer edit section *** (userServiceOrder.dt_action Get start)
                System.DateTime result = this.fdt_action;
                //  *** Start programmer edit section *** (userServiceOrder.dt_action Get end)

                //  *** End programmer edit section *** (userServiceOrder.dt_action Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (userServiceOrder.dt_action Set start)

                //  *** End programmer edit section *** (userServiceOrder.dt_action Set start)
                this.fdt_action = value;
                //  *** Start programmer edit section *** (userServiceOrder.dt_action Set end)

                //  *** End programmer edit section *** (userServiceOrder.dt_action Set end)
            }
        }
        
        /// <summary>
        /// User_service_order.
        /// </summary>
        //  *** Start programmer edit section *** (userServiceOrder.service_order_id CustomAttributes)

        //  *** End programmer edit section *** (userServiceOrder.service_order_id CustomAttributes)
        [PropertyStorage(new string[] {
                "service_order_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.serviceOrder service_order_id
        {
            get
            {
                //  *** Start programmer edit section *** (userServiceOrder.service_order_id Get start)

                //  *** End programmer edit section *** (userServiceOrder.service_order_id Get start)
                DataLine.xgvlk98.serviceOrder result = this.fservice_order_id;
                //  *** Start programmer edit section *** (userServiceOrder.service_order_id Get end)

                //  *** End programmer edit section *** (userServiceOrder.service_order_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (userServiceOrder.service_order_id Set start)

                //  *** End programmer edit section *** (userServiceOrder.service_order_id Set start)
                this.fservice_order_id = value;
                //  *** Start programmer edit section *** (userServiceOrder.service_order_id Set end)

                //  *** End programmer edit section *** (userServiceOrder.service_order_id Set end)
            }
        }
        
        /// <summary>
        /// User_service_order.
        /// </summary>
        //  *** Start programmer edit section *** (userServiceOrder.user_id CustomAttributes)

        //  *** End programmer edit section *** (userServiceOrder.user_id CustomAttributes)
        [PropertyStorage(new string[] {
                "user_id"})]
        [NotNull()]
        public virtual DataLine.xgvlk98.usr user_id
        {
            get
            {
                //  *** Start programmer edit section *** (userServiceOrder.user_id Get start)

                //  *** End programmer edit section *** (userServiceOrder.user_id Get start)
                DataLine.xgvlk98.usr result = this.fuser_id;
                //  *** Start programmer edit section *** (userServiceOrder.user_id Get end)

                //  *** End programmer edit section *** (userServiceOrder.user_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (userServiceOrder.user_id Set start)

                //  *** End programmer edit section *** (userServiceOrder.user_id Set start)
                this.fuser_id = value;
                //  *** Start programmer edit section *** (userServiceOrder.user_id Set end)

                //  *** End programmer edit section *** (userServiceOrder.user_id Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "user_service_orderE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View user_service_orderE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("user_service_orderE", typeof(DataLine.xgvlk98.userServiceOrder));
                }
            }
            
            /// <summary>
            /// "user_service_orderL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View user_service_orderL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("user_service_orderL", typeof(DataLine.xgvlk98.userServiceOrder));
                }
            }
        }
    }
}
