//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLine.xgvlk98
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// user_role.
    /// </summary>
    //  *** Start programmer edit section *** (user_role CustomAttributes)

    //  *** End programmer edit section *** (user_role CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class user_role : ICSSoft.STORMNET.DataObject
    {
        
        private DataLine.xgvlk98.role frole_id;
        
        private DataLine.xgvlk98.usr fuser_id;
        
        //  *** Start programmer edit section *** (user_role CustomMembers)

        //  *** End programmer edit section *** (user_role CustomMembers)

        
        /// <summary>
        /// user_role.
        /// </summary>
        //  *** Start programmer edit section *** (user_role.role_id CustomAttributes)

        //  *** End programmer edit section *** (user_role.role_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.xgvlk98.role role_id
        {
            get
            {
                //  *** Start programmer edit section *** (user_role.role_id Get start)

                //  *** End programmer edit section *** (user_role.role_id Get start)
                DataLine.xgvlk98.role result = this.frole_id;
                //  *** Start programmer edit section *** (user_role.role_id Get end)

                //  *** End programmer edit section *** (user_role.role_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (user_role.role_id Set start)

                //  *** End programmer edit section *** (user_role.role_id Set start)
                this.frole_id = value;
                //  *** Start programmer edit section *** (user_role.role_id Set end)

                //  *** End programmer edit section *** (user_role.role_id Set end)
            }
        }
        
        /// <summary>
        /// user_role.
        /// </summary>
        //  *** Start programmer edit section *** (user_role.user_id CustomAttributes)

        //  *** End programmer edit section *** (user_role.user_id CustomAttributes)
        [NotNull()]
        public virtual DataLine.xgvlk98.usr user_id
        {
            get
            {
                //  *** Start programmer edit section *** (user_role.user_id Get start)

                //  *** End programmer edit section *** (user_role.user_id Get start)
                DataLine.xgvlk98.usr result = this.fuser_id;
                //  *** Start programmer edit section *** (user_role.user_id Get end)

                //  *** End programmer edit section *** (user_role.user_id Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (user_role.user_id Set start)

                //  *** End programmer edit section *** (user_role.user_id Set start)
                this.fuser_id = value;
                //  *** Start programmer edit section *** (user_role.user_id Set end)

                //  *** End programmer edit section *** (user_role.user_id Set end)
            }
        }
    }
}
